# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jarvius.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DesktopAI(object):
    def setupUi(self, DesktopAI):
        DesktopAI.setObjectName("DesktopAI")
        DesktopAI.resize(908, 557)
        self.centralwidget = QtWidgets.QWidget(DesktopAI)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-10, -30, 851, 601))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(10, 20, 311, 201))
        self.Bg_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.Bg_2.setText("")
        self.Bg_2.setObjectName("Bg_2")
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(330, 20, 281, 201))
        self.Bg_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.Bg_3.setText("")
        self.Bg_3.setObjectName("Bg_3")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 30, 291, 181))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 261, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/ExtraGui/live.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(50, 240, 441, 321))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/VoiceReg/__1.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.Bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_5.setGeometry(QtCore.QRect(620, 20, 221, 201))
        self.Bg_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.Bg_5.setText("")
        self.Bg_5.setObjectName("Bg_5")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(630, 32, 201, 181))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/ExtraGui/Earth.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.Text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_time.setGeometry(QtCore.QRect(590, 470, 211, 41))
        self.Text_time.setStyleSheet("background-color: transparent;\n"
"boarder_radius:none;")
        self.Text_time.setObjectName("Text_time")
        self.Bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_6.setGeometry(QtCore.QRect(590, 470, 221, 51))
        self.Bg_6.setText("")
        self.Bg_6.setPixmap(QtGui.QPixmap("G.U.I Material-20221222T124901Z-001/G.U.I Material/B.G/gyhf.jpg"))
        self.Bg_6.setScaledContents(True)
        self.Bg_6.setObjectName("Bg_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(434, 330, 161, 71))
        self.pushButton.setStyleSheet("font: 22pt \"Niagara Solid\";\n"
"background-color: rgb(0, 170, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 330, 161, 71))
        self.pushButton_3.setStyleSheet("font: 22pt \"Niagara Solid\";\n"
"background-color: rgb(0, 170, 255);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.Bg_1.raise_()
        self.gif_3.raise_()
        self.Bg_2.raise_()
        self.Bg_3.raise_()
        self.gif_1.raise_()
        self.label.raise_()
        self.Bg_5.raise_()
        self.gif_4.raise_()
        self.Text_time.raise_()
        self.Bg_6.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        DesktopAI.setCentralWidget(self.centralwidget)

        self.retranslateUi(DesktopAI)
        QtCore.QMetaObject.connectSlotsByName(DesktopAI)

    def retranslateUi(self, DesktopAI):
        _translate = QtCore.QCoreApplication.translate
        DesktopAI.setWindowTitle(_translate("DesktopAI", "MainWindow"))
        self.pushButton.setText(_translate("DesktopAI", "Start"))
        self.pushButton_3.setText(_translate("DesktopAI", "End"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesktopAI = QtWidgets.QMainWindow()
    ui = Ui_DesktopAI()
    ui.setupUi(DesktopAI)
    DesktopAI.show()
    sys.exit(app.exec_())
